### ISSUE TITLE
class Twitter managing errors in Laravel 5 fails

### ISSUE THREAD

**Issue by sergiodebcn** [thujohn/twitter#70]
In method query, this code fails when I get an error code from twitter api, php shows ErrorException in Twitter.php line 276:
Undefined index: message.

```
if (isset($response['code']) && $response['code'] != 200)
		{
			$_response = $this->jsonDecode($response['response'], true);

			if (array_key_exists('errors', $_response))
			{
				$error_msg = $_response['message'];
			}
			else
			{
				$error_msg = $_response['error'];
			}

			$this->log('ERROR_CODE : '.$response['code']);
			$this->log('ERROR_MSG : '.$error_msg);

			throw new Exception('['.$response['code'].'] '.$error_msg, $response['code']);
		}
```
My $_response prints;

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => 63
                    [message] => User has been suspended.
                )

        )

)
```

If I change code to read the array response correctly, it works

$error_msg = $_response['errors'][0]['message'];
$error_msg = $_response['errors'][0]['code'];

**Comment by thujohn** [comment]
Hi.

It should be fixed now

**Comment by sergiodebcn** [comment]
I've been using the package last months. Very useful, Thanks for the job done.

**Comment by sergiodebcn** [comment]
In my code I do multiple Requests to  Twitter::getUsers() inside a foreach.
With the old code when a Request fails, In the package code non Exception is thrown and I manage error exceptions.

Now with the throw Exception at line 288, I am not able to manage this to continue with the code after the Exception.

**Comment by sergiodebcn** [comment]
OK, with a try.. catch... in my code I'm solving this.

**Comment by puntofisso** [comment]
Still seeing this in Laravel 5.3 - is try/catch the only way?
Also, not quite sure what happens to trigger this error, given that exception seems to be about duplicate messages (and I've made sure this is not the case by using a test account with no tweets). Any idea?

**Comment by asimshahzadmjc** [comment]
Even try catch is not working in my case application just crashes @thujohn My Laravel installation is 5.3
